# -*- coding: utf-8 -*-
"""anderson_lab_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhNHZj_wjsl6ySMObEgQ7sspBnXq8nqK
"""

board = [['_', '_', '_'], ['_', '_', '_'],['_', '_', '_']]  # this list contains 3 lists, each of 3 elements, each element being a single character

def print_board():
  print(board[0])
  print(board[1])
  print(board[2])

def check_mark():
  pass

def place_mark():
  pass

def check_win():
  pass

def main():
  print('Tic tac toe battle, start!')
  print_board()

main()